# server.port=8081
# spring.application.name=backend
# spring.datasource.url=jdbc:postgresql://localhost:5432/diya_db
# spring.datasource.username=diya_user
# spring.datasource.password=diya123
# spring.datasource.driver-class-name=org.postgresql.Driver
# # spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=create 
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# server.address=0.0.0.0

server.address=0.0.0.0
spring.application.name=backend
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect